name: .NET CI + SonarCloud (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Build & SonarCloud (on Windows)
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout source
      uses: actions/checkout@v3

    - name: 🧰 Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: 📦 Restore dependencies
      run: dotnet restore

    - name: 🧪 Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: ▶ Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        #dotnet-sonarscanner begin /k:"mkharrat-dev_MazeSolver" /o:"mkharrat-dev" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /s:sonar-project.properties
        dotnet-sonarscanner begin /k:"mkharrat-dev_MazeSolver" /o:"mkharrat-dev" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: 🛠️ Build
      run: dotnet build AppTest.sln --configuration Debug --no-restore
      
    - name: 🛠️ Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: 🧪 Test
      run: dotnet test AppTest.sln --no-build --verbosity normal

    - name: 🧪 Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: 🛑 End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

